INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('101', 'IT', 'IT Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('102', 'HR', 'HR Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('103', 'Finance', 'Finance Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('104', 'Sales', 'Sales Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('105', 'Development', 'Development Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('106', 'Network', 'Network Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('107', 'Security', 'Security Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('108', 'Admin', 'Admin Department', 'ACT');
INSERT INTO `department` (`id`, `name`, `description`, `status`) VALUES ('109', 'Product', 'Product Department', 'ACT');